#!/usr/bin/env python3

import sys
import re

from collections import defaultdict

import deepcut


PATTERN = r'/([0-9]{4})-([0-9]{2})-([0-9]{2})-(.*)\.md'

by_y = defaultdict(int)
by_ym = defaultdict(int)

for filename in sys.argv[1:]:
    content = open(filename).read()
    year, month, day, title = re.findall(PATTERN, filename)[0]
    words = deepcut.tokenize(content)
    by_y[year] += len(words)
    by_ym[year,month] += len(words)
    print(f'{title}: {len(words)}')

print()
for y, values in sorted(by_y.items()):
    print(f'{y}: {values}')

print()
for ym, values in sorted(by_ym.items()):
    print(f'{ym}: {values}')
